spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: mysql
  datasource:
    url: jdbc:mysql://localhost:3306/nias?useUnicode=true&characterEncoding=utf-8&serverTimezone=Hongkong
    username: nias
    password: Nias123687459
    driver-class-name: com.mysql.cj.jdbc.Driver

  main:
    allow-bean-definition-overriding: true